INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);
INSERT INTO users (name, age) VALUES ("Aname", 21);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A title', 'A category', 500.00, '01-01-01', '01-02-01');

INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10.00, 1, 2);
